### ISSUE TITLE
targetSdkVersion 28

### ISSUE THREAD

**Issue by tiekouv** [AltimitSystems/mv-android-client#13]
não sei falar ingles sou brasileiro, descobri que tem que colocar isso no projeto para a google play aceitar em dispositivos android inferior ao 8.0

**Comment by felixjones** [comment]
I added targetSdkVersion to the default builds, does this fix the problem?

**Comment by tiekouv** [comment]
now it's working correctly, thanks

Em sáb, 9 de fev de 2019 11:49 AM, Felix Jones <notifications@github.com>
escreveu:
