### ISSUE TITLE
Add gamepad on screen

### ISSUE THREAD

**Issue by AyraHikari** [AltimitSystems/mv-android-client#16]
In RPG Maker MV, someone made a gamepad plugins, but still it not good enough, it doesn't support multi-touch or another limitations like show on maps only (since it showed by event), even when i test another gamepad plugin with support in menu, it will conflict on another plugins.
So i think an internal gamepad in android client is a good idea.
Can you do it for everyone please?
Thank you

**Comment by felixjones** [comment]
There was a time when we considered this idea, however the MV Android Client should only be focused on providing the minimal required run-time for Android, it's not our job to decide the best input system for other people's games, the game developers should find or write their own Plugins for their needs.

In the future, I might write the Plugin as a separate project from MV Android Client, but generally decisions like this should be left to the game developers, not us.
