### ISSUE TITLE
admob

### ISSUE THREAD

**Issue by tiekouv** [AltimitSystems/mv-android-client#17]
I would make a generous donation if you added an easy way to put the admob code in the project. I have games on google play, but all are paid, I would earn more with advertisement. please.

**Comment by felixjones** [comment]
We do not provide commercial support for MV Android Client.
AdMob has a simple guide for implementing it on Android: https://developers.google.com/admob/android/quick-start if you find the guide too difficult then I suggest you privately find a developer who can spend the time to implement this for you.
